### ISSUE TITLE
Context association

### ISSUE THREAD

**Issue by diblaauw** [ChrisdeG/DropZone#4]
For start: Awesome widget! Thanks!
I might be using it wrong - then this is a question, or I bumped into a bug.
I have the DropZone widget (v3, Mx6.0.1) in a Dataview, object called LeadDocument. It's related to an object Lead (Many LeadDocuments to a Lead). In the property association to context I've selected the association from LeadDocument to Lead. Uploading the files works just fine, but generates the following message:

com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"{LEADS.LeadDocument_Lead=12384898975271877}","type":"ChangeAction"}', all database changes executed by this action were rolled back
    at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:189)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"{LEADS.LeadDocument_Lead=12384898975271877}","type":"ChangeAction"}', all database changes executed by this action were rolled back
    at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:36)

Caused by: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"changes":"{LEADS.LeadDocument_Lead=12384898975271877}","type":"ChangeAction"}', all database changes executed by this action were rolled back
    at com.mendix.core.actionmanagement.CoreAction.processErrorState(CoreAction.java:303)

Caused by: java.lang.IllegalArgumentException: requirement failed: Reference 'LEADS.LeadDocument_Lead' only accepts ids of type 'LEADS.Lead' (Id '[MendixIdentifier:: id=12384898975271877 objectType=LEADS.LeadDocument entityID=44]' is not allowed).
    at scala.Predef$.require(Predef.scala:219)
    at com.mendix.core.objectmanagement.member.MendixObjectReference.setValue(MendixObjectReference.scala:17)
    at com.mendix.core.objectmanagement.member.MendixObjectReference.setValue(MendixObjectReference.scala:11)
    at com.mendix.core.objectmanagement.MendixObjectMemberImpl.parseValueFromString(MendixObjectMemberImpl.java:244)
    at com.mendix.core.action.user.Changer$class.setMemberValue(Changer.scala:59)
    at com.mendix.core.action.user.Changer$class.changeMember(Changer.scala:29)
    at com.mendix.core.action.user.ChangeAction.changeMember(ChangeAction.scala:10)
    at com.mendix.core.action.user.ChangeAction$$anonfun$executeAction$1.apply(ChangeAction.scala:32)
    at com.mendix.core.action.user.ChangeAction$$anonfun$executeAction$1.apply(ChangeAction.scala:31)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at com.mendix.core.action.user.ChangeAction.executeAction(ChangeAction.scala:31)
    at com.mendix.core.action.user.ChangeAction.executeAction(ChangeAction.scala:10)
    at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
    at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
    at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
    at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:179)
    at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
    at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:185)
    at com.mendix.core.component.InternalCore.change(InternalCore.java:117)
    at com.mendix.webui.actions.client.ChangeAction.execute(ChangeAction.scala:30)
    at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:322)
    at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
    at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
    at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
    at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
    at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
    at scala.util.Try$.apply(Try.scala:191)
    at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ChrisdeG** [comment]
Hello Dirk,

The association should be from leaddocument to lead. Don't should a reference set but a reference.

Regards,
Chris

**Comment by diblaauw** [comment]
Hi Chris,

Thanks for the reply. The way you've described it, is exactly the way I've implemented it - that's what generated the above error.

Kind regards,
Dirk

**Comment by ChrisdeG** [comment]
Hi Dirk,



Have you checked the access rights?



I can send a demo project.



Met vriendelijke groet,





[image: FlowFabric] <http://www.flowfabric.com/>



Chris de Gelder

Business Consultant

cdgelder@flowfabric.com

+31(0)6 - 461 39 865



*Van:* Dirk Blaauw [mailto:notifications@github.com]
*Verzonden:* Thursday, January 7, 2016 2:40 PM
*Aan:* ChrisdeG/DropZone
*CC:* ChrisdeG
*Onderwerp:* Re: [DropZone] Context association (#4)



Hi Chris,

Thanks for the reply. The way you've described it, is exactly the way I've
implemented it - that's what generated the above error.

Kind regards,
Dirk

—
Reply to this email directly or view it on GitHub
<https://github.com/ChrisdeG/DropZone/issues/4#issuecomment-169666652>.[image:
Afbeelding verwijderd door afzender.]

**Comment by diblaauw** [comment]
Hey Chris,

Yeah, I did, should work just fine.
Sample project would be appreciated, that way I can check for any differences!

Kind regards,


[Description: Description: Description: Description: logo_HTC_mail_150x130.png]Dirk Blaauw
Senior Consultant
Mendix Engineer, Architect & Community Lead

Capgemini The Netherlands | Utrecht – Leidsche Rijn
Tel.: +31 30 689 63 13 – Mob.: + 31 6 29 52 80 92
www.capgemini.com<http://www.capgemini.com/>
People matter, results count.
